export const GET_POKEMONS = "GET_POKEMONS";
export const GET_DETAIL = "GET_DETAIL";
export const CLEAR_DETAIL = "CLEAR_DETAIL";
export const GET_TYPES = "GET_TYPES"
export const CREATE_POKEMON = "CREATE_POKEMON"
export const GET_POKE_BY_NAME = "GET_POKE_BY_NAME"
export const CLEAR_POKE_BY_NAME = "CLEAR_POKE_BY_NAME"
export const FILTER_BY_ORIGIN = "FILTER_BY_ORIGIN"
export const FILTER_BY_TYPE = "FILTER_BY_TYPE"
export const CLEAR_FILTERED = "CLEAR_FILTERED"
export const ORDER_BY_NAME = "ORDER_BY_NAME"
export const ORDER_BY_ATTACK = "ORDER_BY_ATTACK"
export const SET_ORIGIN_VALUE = "SET_ORIGIN_VALUE"
export const SET_TYPE_VALUE = "SET_TYPE_VALUE"





